[package]
name = "wasm-planet-generator"
version = "0.1.0"
authors = ["Victor Rebiard--Crépin <victor.rebiardcrepin@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = { version = "^0.2", features = ["serde-serialize"] }

serde = "^1.0.59"
serde_derive = "^1.0.59"

rand = "^0.7.3"
getrandom = { version = "*", features = ["wasm-bindgen"] }
noise = "0.6.0"

console_error_panic_hook = { version = "0.1.1", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.2"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
debug = true
